content/blog/2018-09-01-grammar-of-graphics.md

typo description

---

config.toml

removed flick and rss links. facebook/twitter was already removed.

remove flickr link

---

content/blog/2018-09-01-grammar-of-graphics.md

sorry didn't know how to properly edit simply the article, hope this is fine...

grammar-graphics-typo

---

content/blog/2018-09-01-grammar-of-graphics.md

Thanks for your reviews gaillezzz ...
I made the PR right now, but I'll wait for your confirmation before merging the branch.

Additional corrections go g

---

content/blog/2018-11-17-hackathon-winners-presentation.md

Voici les changements que je te propose pour ma dernière lecture. Je sais qu'on voulait pas changer trop de tournures de phrases, mais j'ai fais quelques modifs que je considère très mineures, mais qui je pense peuvent aider à la lecture de certaines parties.

Proposition de dernière minute

---

config.toml

Fix the baseurl param

---

README.md

suggestion of modification for the readme to prevent corruption of the repository

procedure to add post modification suggestion

---

config.toml
content/about/_index.md
themes/hugo-future-imperfect/layouts/partials/footer.html
themes/hugo-future-imperfect/layouts/partials/sidebar.html

could not introduce the inline code format for Hello, World! in the side panel of home.
J'ai changé le slogan pour le générique .layer.

Meet. Learn. Share. + inline code for Hello, World! in about tab

---

config.toml

Change email adress for info. Meant to close #55

Change the email adress to point to our new adress box

---

content/blog/2018-12-07-ethical-ai-insurance.md

Quelques propositions pour la section segmentation. Pas obliger de les accepter, je te laisse voir. Je vais essayer de commenter les différents points dans la section suivante dans les prochains jours aussi.

Add some stuffs in the segmentation section to talk about ratemaking

---

static/css/add-on.css
themes/hugo-future-imperfect/layouts/partials/footer-category.html
themes/hugo-future-imperfect/layouts/partials/language-switcher.html
themes/hugo-future-imperfect/layouts/partials/sidebar.html
themes/hugo-future-imperfect/layouts/taxonomy/category.terms.html

J'ai changé l'icône de FR / EN parce que les couleurs étaient juste too much pour le look du blog je pense... ( link to issue #34 )
J'ai aussi changé le look des catégories (le font-size pis les couleurs) parce que ça suivait pas le reste du style dans le site.

Changed translate link and category look

---

content/contact/_index.fr.md
content/contact/_index.md
i18n/en.toml
i18n/fr.toml
static/css/add-on.css
themes/hugo-future-imperfect/layouts/contact/list.html

Tout ce qui me manque c'est l'adresse legit de dotLayer et on est en business!
ᕕ( ᐛ )ᕗ
J'ai corrige la traduction et j'ai change un peu le look. Ca me semble pas pire pas pire :)
ISSUE: Update contact page look #80

Update contact page look

---

content/about/_index.fr.md
content/about/_index.md

Il reste encore de l'édition... et le traduire pour l'anglais. J'aimeras aussi qu'on update les versions dans config.toml.
Vous en pensez quoi à date? Des suggestions?

draft 1 FR

---

themes/hugo-future-imperfect/layouts/itemized/content-single.html
themes/hugo-future-imperfect/layouts/partials/share-links.html
themes/hugo-future-imperfect/layouts/partials/share-menu.html
themes/hugo-future-imperfect/layouts/post/content-single.html
themes/hugo-future-imperfect/static/css/main.css

Je trouvais que les couleurs pis les shapes de boutons clashaient un peu dans les header d'articles alors j'ai essayé de quoi... Dites-moi tout! On aime ou on n'aime pas?
(link to issue _WebSite Maintenance #86_)
**AvAnT**
**ApRèS**

New design social share button? Who's in?

---

layouts/post/header.html

J'ai fait disparaître les dates avec mes merges... OUPSSSS

Oupsie dates disparues

---

HOWTO.md
LICENSE
README.md

Added CC-By license to the blog post (#96).
Added a HOWTO based on the tutorial in the README.
Updated README with the new about of .Layer.

add CC-BY license

---

content/blog/2019-12-19-recap-2019/index.fr.md

Il en reste peut-être mais au moins j'aurais essayé.

Correction des fautes qui font mal aux yeux

---

content/blog/2020-03-04-what-is-wrong-with-sklearn/index.en.md
layouts/partials/language-switcher.html
static/css/add-on.css
static/css/main.css

Issue #118 
Au lieu d'afficher un menu contextuel, c'est juste le bouton du language disponible. Ca va aller mieux sur mobile surtout. 
Pis si pas de traduction disponible,

Change comportement btn language

---

content/about/_index.en.md
content/about/_index.fr.md
layouts/partials/sidebar.html

Samperochkin patch about

---

i18n/en.toml
i18n/fr.toml
layouts/404.html
layouts/partials/form/contribute.html
static/css/404.css

En plus d'avoir ecrit "Intruction" au lieu de "Instruction"...
Big LOL!
Issue #125

Fix link in Contribute

---

content/blog/2020-10-30-reproducibility-in-ml-a-talk/index.fr.md

Il manque juste le lien Utube.

Post rapide sur un webinaire sur la reproductibilité en apprentissage automatique
